### ISSUE TITLE
Crash when opening backpacks containing items

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MrTJP/ProjectRed#1207]
When opening a backpack for the first time, everything works normally. If you place an item inside the backpack, close it and open it again, it will crash.

Log file: https://pastebin.com/kYW5Kcch

Crash report: https://pastebin.com/1BUdY26L

**Comment by JoshHawley** [comment]
I am experiencing this same bug. The client crashes (as seen above), but on the server (FTB Beyond 1.10.0) I also see the exact same stack trace.

**Comment by MrTJP** [comment]
Fixed in latest commit, wait for release

**Comment by ResqDiver1317** [comment]
We are having this same problem which is how I found this issue thread. I was wondering if there was an estimated timeline for the next release that fixes this bug?

**Comment by Cmoor** [comment]
I would like to add too that we are also having this issue. Here is my crash report:
https://hastebin.com/teyupojiwe.sql

As TheDeviantCrafter stated, it only happens when the backpack has items inside it. Other wise I could open it constantly without issue, while it's empty.

ProjectRed v1.10.2-4.8.4.49

**Comment by DatsiK96** [comment]
Just FYI, this is still an issue.

java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192) ~[ArrayOps$ofRef$.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192) ~[ArrayOps$ofRef.class:?]
        at scala.collection.GenSeqLike$class.isDefinedAt(GenSeqLike.scala:72) ~[GenSeqLike$class.class:?]
        at scala.collection.mutable.ArrayOps$ofRef.isDefinedAt(ArrayOps.scala:186) ~[ArrayOps$ofRef.class:?]
        at mrtjp.core.inventory.TInventory$$anonfun$loadInv$1.apply$mcVI$sp(invtraits.scala:89) ~[TInventory$$anonfun$loadInv$1.class:?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[Range.class:?]
        at mrtjp.core.inventory.TInventory$class.loadInv(invtraits.scala:84) ~[TInventory$class.class:?]
        at mrtjp.projectred.exploration.BagInventory.loadInv(items.scala:114) ~[BagInventory.class:?]
        at mrtjp.core.inventory.TInventory$class.loadInv(invtraits.scala:80) ~[TInventory$class.class:?]
        at mrtjp.projectred.exploration.BagInventory.loadInv(items.scala:114) ~[BagInventory.class:?]
        at mrtjp.projectred.exploration.BagInventory.loadInventory(items.scala:125) ~[BagInventory.class:?]
        at mrtjp.projectred.exploration.BagInventory.<init>(items.scala:116) ~[BagInventory.class:?]
        at mrtjp.projectred.exploration.ItemBackpack$.createContainer(items.scala:77) ~[ItemBackpack$.class:?]
        at mrtjp.projectred.exploration.ItemBackpack.openGui(items.scala:54) ~[ItemBackpack.class:?]
        at mrtjp.projectred.exploration.ItemBackpack.func_77659_a(items.scala:48) ~[ItemBackpack.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163) ~[adz.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
[18:45:06] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_151]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_151]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_151]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_151]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
