### ISSUE TITLE
[Bug] Intergration crash on startup

### ISSUE THREAD

**Issue by border999** [MrTJP/ProjectRed#1870]
### Minecraft version

1.20.x

### CodeChickenLib version

CodeChickenLib-1.20.1-4.4.0.512-universal

### CBMultipart version

CBMultipart-1.20.1-3.3.0.146-universal

### ProjectRed version

ProjectRed-1.20.1-4.19.0-beta+3-integration

### What happened?

"Crash" during startup

### Crash log

https://gist.github.com/border999/6c3e1063ee0d8db2fd13a804abdb9d4f -debug.log
https://gist.github.com/border999/4f19503dba9c51b992f60cbe287157b2 -latest.log

### How do you make it happen again?

attempt to start game.

**Comment by MrTJP** [comment]
Hi. Are you using a texture/resource pack for Project Red? Looks like some models are missing. Specifically, the Gate models are not found.

**Comment by ashi0-a** [comment]
Try just turning it off and on in curseforge, it works for me

**Comment by border999** [comment]
not using curseforge modloader. I do not have a texture pack or anything for projectRed

**Comment by I2pRandom** [comment]
I seem to be getting the same issue, inconsistent random crashing on startup.
[debug.log](https://github.com/user-attachments/files/16682741/debug.log)
[latest.log](https://github.com/user-attachments/files/16682742/latest.log)
[crash-2024-08-20_16.50.26-client.txt](https://github.com/user-attachments/files/16682743/crash-2024-08-20_16.50.26-client.txt)

**Comment by border999** [comment]
I assume this has been fixed in one of the version that has come out in intervening time? Just checking in on this so I know whether or not to close this.

**Comment by FocalFlare** [comment]
> I assume this has been fixed in one of the version that has come out in intervening time? Just checking in on this so I know whether or not to close this. Can't confirm it's fixed on my end because I'm dealing with a different and new crash from this mod that I submitted an issue ticket for a few minutes ago.

_For such issue (in my case it's with Entity Texture Features, as from #1888), I personally wouldn't get your hopes up for it to be addressed any time soon. I know that sounds a bit cold to say, but I had to self-close my issue as not plannedas I assumed that it wouldn't be looked into._ 😔

**Comment by border999** [comment]
https://github.com/MrTJP/ProjectRed/issues/1893

**Comment by MrTJP** [comment]
For those of you still having this issue, we may have found the cause in CCL. Please try the test jar that @covers1624 has uploaded on this issue:

https://github.com/TheCBProject/CodeChickenLib/issues/460

**Comment by MrTJP** [comment]
Many people have reported that CCL's patch has fixed similar issues on other mods. Closing..
